{{- range .Values.nodetemplates }}
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: {{ .name }}
  labels: 
    name: {{ .name }}
    {{- include "karpenter-provisioner.labels" $ | nindent 4 }}
spec:
{{- with .spec }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
