{{- range .Values.nodePools }}
---
{{- $consolidationPolicy := .consolidationPolicy | default "WhenEmptyOrUnderutilized" }}
{{- $consolidateAfter := .consolidateAfter | default "60s" }}
{{- $expireAfter := .expireAfter | default "720h" }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}
  labels: 
    name: {{ .name }}
    {{- include "karpenter-provisioner.labels" $ | nindent 4 }}
spec:
  {{- with .weight }}
  weight: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .nodeClassName }}
      expireAfter: {{ $expireAfter }}
      {{- with .terminationGracePeriod }}
      terminationGracePeriod: {{ . }}
      {{- end }}
      {{- with .taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .startupTaints }}
      startupTaints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .requirements }}
      requirements:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  disruption:
    consolidationPolicy: {{ $consolidationPolicy }}
    consolidateAfter: {{ $consolidateAfter }}
    {{- with .budgets }}
    budgets:
      {{- range . }}
      - nodes: {{ .nodes | quote }}
        {{- with .schedule }}
        schedule: {{ . | quote }}
        {{- end }}
        {{- with .duration }}
        duration: {{ . }}
        {{- end }}
        {{- with .reasons }}
        reasons:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- with .limits }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
