{{- range .Values.provisioners }}
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .name }}
  labels: 
    name: {{ .name }}
    {{- include "karpenter-provisioner.labels" $ | nindent 4 }}
spec:
{{- with .spec }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
