name-template: 'v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
    - 'enhancement'
    # - 'feat'
  patch:
    labels:
    - 'auto-update'
    - 'patch'
    - 'fix'
    - 'bugfix'
    - 'bug'
    - 'hotfix'
    - 'refactor'
    - 'ci'
    - 'build'
    - 'docs'
    - 'test'
    - 'chore'
    - 'feat'
  default: 'patch'

categories:
- title: '🚀 Enhancements'
  labels:
  - 'minor'
  - 'enhancement'
  - 'feat'
- title: '🐛 Bug Fixes'
  labels:
  - 'auto-update'
  - 'patch'
  - 'fix'
  - 'bugfix'
  - 'bug'
  - 'hotfix'
  - 'refactor'
  - 'ci'
  - 'build'
  - 'docs'
  - 'test'
  - 'chore'
- title: '🤖 Automatic Updates'
  labels:
  - 'auto-update'

change-template: |
  <details>
    <summary>$TITLE @$AUTHOR (#$NUMBER)</summary>
    $BODY
  </details>
template: |
  $CHANGES