version: v1

labels:
  - label: "feat"
    matcher:
      title: "^feat:.*"
  - label: "fix"
    matcher:
      title: "^fix:.*"
  - label: "ci"
    matcher:
      title: "^ci:.*"
  - label: "chore"
    matcher:
      title: "^chore:.*"
  - label: "build"
    matcher:
      title: "^build:.*"
  - label: "docs"
    matcher:
      title: "^docs:.*"
  - label: "refactor"
    matcher:
      title: "^refactor:.*"
  - label: "test"
    matcher:
      title: "^test:.*"