formatter: markdown

output:
  file: README.md
  mode: replace
  template: |-
    # terraform-argocd-aws-eks-cluster-bootstrap

    A terraform module to bootstrap apps on AWS EKS using ArgoCD.

    ## Usage

    ```hcl
    module "apps" {
      source              = "git::https://github.com/rallyware/terraform-argocd-aws-eks-cluster-bootstrap.git?ref=master"
      argocd_iam_role_arn = "argocd-role-arn"
      eks_cluster_id      = "staging-cluster"

      argocd_additional_projects = [
        {
          name = "test"
        }
      ]
    }
    ```

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 

    ## License
    The Apache-2.0 license

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
