formatter: markdown

output:
  file: README.md
  mode: replace
  template: |-
    ## Usage

    ```hcl
    module "your_aweasome_resource" {
      source    = ""
      namespace = "sweetops"
      stage     = "production"
      name      = "aweasome"
    }
    ```

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS --> 

    ## License
    The Apache-2.0 license

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true