{{- range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  labels:
    cluster-issuer: {{ .name | quote }}
    {{- include "cert-manager-resources.labels" $ | nindent 4 }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
