{{- range .Values.issuers }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .name }}
  labels:
    cert-manager.io/v1/issuer/name: {{ .name }}
    {{- include "cert-manager-resources.labels" $ | nindent 4 }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
