nameOverride: ""
fullnameOverride: ""

issuers:
  []
  # - name: self-signed
  #   spec:
  #     selfSigned: {}

clusterIssuers:
  []
  # - name: letsencrypt
  #   spec:
  #     acme:
  #       server: https://acme-v02.api.letsencrypt.org/directory
  #       preferredChain: "ISRG Root X1"
  #       privateKeySecretRef:
  #         name: letsencrypt-prod-account-key
  #       email: letsencrypt@rallyware.com
  #       solvers:
  #         - dns01:
  #             cloudflare:
  #               email: letsencrypt@rallyware.com
  #               apiTokenSecretRef:
  #                 name: cloudflare-api-token
  #                 key: cloudflare-api-token
  # - name: self-signed
  #   spec:
  #     selfSigned: {}

certificates:
  []
  # - name: test
  #   spec:
  #     secretName: rw-wildcard
  #     commonName: rallyware.com
  #     dnsNames:
  #       - rallyware.com
  #       - "*.rallyware.com"
  #     issuerRef:
  #       name: some-issuer
  #       kind: ClusterIssuer
  #       group: cert-manager.io
  #     secretTemplate:
  #       annotations:
  #         kubed.appscode.com/sync: "cert-manager-tls=rw-wildcard"

# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates
extraObjects:
  []
  # - apiVersion: secrets-store.csi.x-k8s.io/v1
  #   kind: SecretProviderClass
  #   metadata:
  #     name: argo-events-secrets-store
  #   spec:
  #     provider: aws
  #     parameters:
  #       objects: |
  #         - objectName: "argo-events"
  #           objectType: "secretsmanager"
  #           jmesPath:
  #               - path: "client_id"
  #                 objectAlias: "client_id"
  #               - path: "client_secret"
  #                 objectAlias: "client_secret"
  #     secretObjects:
  #     - data:
  #       - key: client_id
  #         objectName: client_id
  #       - key: client_secret
  #         objectName: client_secret
  #       secretName: argo-events-secrets-store
  #       type: Opaque
  #       labels:
  #         app.kubernetes.io/part-of: argocd
