name: Auto Label

on:
  pull_request_target:

jobs:
  labeler:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v2.0.3 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/labeler.yml