name: Release Drafter

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Notary Action
        uses: docker://aevea/release-notary:0.9.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
